import type { Agent, ActivityEntry } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "blaze",
    name: "Blaze",
    department: "Marketing",
    role: "Content Writer",
    emoji: "🔥",
    status: "online",
    color: "#F97316",
    lastActive: "2 min ago",
    tasksToday: 7,
    description: "Writes blogs, social posts, and email newsletters on-brand and fast.",
    tools: ["Claude", "Web Search", "LinkedIn"],
  },
  {
    id: "pixel",
    name: "Pixel",
    department: "Marketing",
    role: "Visual Director",
    emoji: "🎨",
    status: "idle",
    color: "#A855F7",
    lastActive: "18 min ago",
    tasksToday: 3,
    description: "Creates image prompts, enforces brand guidelines, directs visual assets.",
    tools: ["Claude Vision", "Google Drive"],
  },
  {
    id: "forge",
    name: "Forge",
    department: "Engineering",
    role: "Code Reviewer",
    emoji: "⚙️",
    status: "online",
    color: "#6366F1",
    lastActive: "5 min ago",
    tasksToday: 4,
    description: "Reviews PRs, catches bugs and security issues, posts feedback to GitHub.",
    tools: ["GitHub API", "Claude", "Slack"],
  },
  {
    id: "compass",
    name: "Compass",
    department: "HR",
    role: "Onboarding Guide",
    emoji: "🧭",
    status: "idle",
    color: "#22C55E",
    lastActive: "1 hr ago",
    tasksToday: 1,
    description: "Builds Day 1-30 onboarding plans, answers how-we-work questions.",
    tools: ["Notion", "Google Calendar", "Claude"],
  },
  {
    id: "stride",
    name: "Stride",
    department: "Sales",
    role: "Outreach Specialist",
    emoji: "🚀",
    status: "online",
    color: "#F97316",
    lastActive: "Just now",
    tasksToday: 12,
    description: "Researches prospects, writes cold email sequences and LinkedIn messages.",
    tools: ["Web Search", "LinkedIn", "Claude"],
  },
  {
    id: "ledger",
    name: "Ledger",
    department: "Finance",
    role: "Expense Tracker",
    emoji: "📊",
    status: "idle",
    color: "#14B8A6",
    lastActive: "3 hr ago",
    tasksToday: 2,
    description: "Categorizes expenses, detects anomalies, writes monthly finance summaries.",
    tools: ["CSV Parser", "Google Sheets", "Claude"],
  },
];

export const ACTIVITY: ActivityEntry[] = [
  {
    id: "1",
    agentId: "stride",
    agentName: "Stride",
    agentEmoji: "🚀",
    action: "Drafted 3-email cold sequence for Acme Corp (Series B fintech)",
    timestamp: new Date(Date.now() - 1 * 60 * 1000),
    type: "task",
  },
  {
    id: "2",
    agentId: "forge",
    agentName: "Forge",
    agentEmoji: "⚙️",
    action: "Reviewed PR #14 — requested changes on 2 security issues",
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    type: "task",
  },
  {
    id: "3",
    agentId: "blaze",
    agentName: "Blaze",
    agentEmoji: "🔥",
    action: 'Published blog post: "Why Solo Founders Are Winning in 2026"',
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
    type: "task",
  },
  {
    id: "4",
    agentId: "blaze",
    agentName: "Blaze",
    agentEmoji: "🔥",
    action: "Drafted April newsletter — 450 subscribers queued",
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    type: "task",
  },
  {
    id: "5",
    agentId: "ledger",
    agentName: "Ledger",
    agentEmoji: "📊",
    action: "⚠️ Flagged duplicate Vercel charge ($49) — Apr 3 & Apr 4",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    type: "alert",
  },
  {
    id: "6",
    agentId: "compass",
    agentName: "Compass",
    agentEmoji: "🧭",
    action: "Created 30-day onboarding plan for incoming design contractor",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    type: "task",
  },
  {
    id: "7",
    agentId: "pixel",
    agentName: "Pixel",
    agentEmoji: "🎨",
    action: "Generated 4 hero image prompts for product launch campaign",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    type: "task",
  },
  {
    id: "8",
    agentId: "forge",
    agentName: "Forge",
    agentEmoji: "⚙️",
    action: "Approved PR #13 — dashboard routing refactor ✅",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    type: "task",
  },
];
